version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  php-fpm:
    build: ./php
    volumes:
      - ./public:/var/www/html

  php-cli:
    image: php:8.2-cli
    volumes:
      - ./public:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php"]
    tty: true